package GUI;

import BLL.ThanhVienBLL;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author lamquoc
 */
public class MainFrame extends javax.swing.JFrame {

    private int mouseX, mouseY;
    private int totalPage;
    

    /**
     * Creates new form MainFrame
     *
     * @throws java.sql.SQLException
     */
    public MainFrame() throws SQLException {
        initComponents();

        showFunction(1);
        
        this.requestFocusInWindow();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        LeftMenu = new javax.swing.JPanel();
        Panel_QLTV = new javax.swing.JPanel();
        Label_QLTV_icon = new javax.swing.JLabel();
        Label_QLTV = new javax.swing.JLabel();
        Panel_QLTB = new javax.swing.JPanel();
        Label_QLTB_icon = new javax.swing.JLabel();
        Label_QLTB = new javax.swing.JLabel();
        Panel_QLVP = new javax.swing.JPanel();
        Label_VP_icon = new javax.swing.JLabel();
        Label_VP = new javax.swing.JLabel();
        Panel_TK = new javax.swing.JPanel();
        Label_TK_icon = new javax.swing.JLabel();
        Label_TK = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CloseBtn = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        Background.setBackground(new java.awt.Color(255, 255, 255));

        LeftMenu.setBackground(new java.awt.Color(30, 40, 57));
        LeftMenu.setMinimumSize(new java.awt.Dimension(0, 10));

        Panel_QLTV.setBackground(new java.awt.Color(100, 113, 135));
        Panel_QLTV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_QLTV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_QLTVMouseClicked(evt);
            }
        });

        Label_QLTV_icon.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Label_QLTV_icon.setForeground(new java.awt.Color(255, 255, 255));
        Label_QLTV_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Label_QLTV.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Label_QLTV.setForeground(new java.awt.Color(255, 255, 255));
        Label_QLTV.setText("Quản lý thành viên");

        javax.swing.GroupLayout Panel_QLTVLayout = new javax.swing.GroupLayout(Panel_QLTV);
        Panel_QLTV.setLayout(Panel_QLTVLayout);
        Panel_QLTVLayout.setHorizontalGroup(
            Panel_QLTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_QLTVLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Label_QLTV_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Label_QLTV, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_QLTVLayout.setVerticalGroup(
            Panel_QLTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_QLTV_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(Panel_QLTVLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Label_QLTV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Panel_QLTB.setBackground(new java.awt.Color(30, 40, 57));
        Panel_QLTB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_QLTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_QLTBMouseClicked(evt);
            }
        });

        Label_QLTB_icon.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Label_QLTB_icon.setForeground(new java.awt.Color(255, 255, 255));
        Label_QLTB_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Label_QLTB.setBackground(new java.awt.Color(227, 228, 230));
        Label_QLTB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Label_QLTB.setForeground(new java.awt.Color(255, 255, 255));
        Label_QLTB.setText("Quản lý thiết bị");

        javax.swing.GroupLayout Panel_QLTBLayout = new javax.swing.GroupLayout(Panel_QLTB);
        Panel_QLTB.setLayout(Panel_QLTBLayout);
        Panel_QLTBLayout.setHorizontalGroup(
            Panel_QLTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_QLTBLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Label_QLTB_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Label_QLTB, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_QLTBLayout.setVerticalGroup(
            Panel_QLTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_QLTB_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(Panel_QLTBLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Label_QLTB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Panel_QLVP.setBackground(new java.awt.Color(30, 40, 57));
        Panel_QLVP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_QLVP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_QLVPMouseClicked(evt);
            }
        });

        Label_VP_icon.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Label_VP_icon.setForeground(new java.awt.Color(255, 255, 255));
        Label_VP_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Label_VP.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Label_VP.setForeground(new java.awt.Color(255, 255, 255));
        Label_VP.setText("Quản lý vi phạm");

        javax.swing.GroupLayout Panel_QLVPLayout = new javax.swing.GroupLayout(Panel_QLVP);
        Panel_QLVP.setLayout(Panel_QLVPLayout);
        Panel_QLVPLayout.setHorizontalGroup(
            Panel_QLVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_QLVPLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Label_VP_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Label_VP, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_QLVPLayout.setVerticalGroup(
            Panel_QLVPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_VP_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(Panel_QLVPLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Label_VP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Panel_TK.setBackground(new java.awt.Color(30, 40, 57));
        Panel_TK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_TK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_TKMouseClicked(evt);
            }
        });

        Label_TK_icon.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Label_TK_icon.setForeground(new java.awt.Color(255, 255, 255));
        Label_TK_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Label_TK.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Label_TK.setForeground(new java.awt.Color(255, 255, 255));
        Label_TK.setText("Thống kê");

        javax.swing.GroupLayout Panel_TKLayout = new javax.swing.GroupLayout(Panel_TK);
        Panel_TK.setLayout(Panel_TKLayout);
        Panel_TKLayout.setHorizontalGroup(
            Panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_TKLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Label_TK_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Label_TK, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_TKLayout.setVerticalGroup(
            Panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_TK_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(Panel_TKLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Label_TK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Kannada MN", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PROJECT2");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 20));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        jSeparator1.setRequestFocusEnabled(false);
        jSeparator1.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout LeftMenuLayout = new javax.swing.GroupLayout(LeftMenu);
        LeftMenu.setLayout(LeftMenuLayout);
        LeftMenuLayout.setHorizontalGroup(
            LeftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_QLTV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel_QLTB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel_TK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LeftMenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(LeftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addComponent(Panel_QLVP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LeftMenuLayout.setVerticalGroup(
            LeftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftMenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(Panel_QLTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Panel_QLTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Panel_QLVP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Panel_TK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CloseBtn.setBackground(new java.awt.Color(255, 255, 255));
        CloseBtn.setFont(new java.awt.Font("Kannada MN", 1, 24)); // NOI18N
        CloseBtn.setForeground(new java.awt.Color(67, 78, 97));
        CloseBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseBtn.setText("X");
        CloseBtn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                CloseBtn.setForeground(Color.RED);
            }

            @Override
            public void mouseExited(MouseEvent e) {

                CloseBtn.setForeground(new Color(0x1E2839));
            }
        });
        CloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 862, Short.MAX_VALUE)
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(LeftMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(LeftMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(CloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBtnMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen() - mouseX;
        int y = evt.getYOnScreen() - mouseY;
        setLocation(x, y);
    }//GEN-LAST:event_formMouseDragged

    private void Panel_TKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_TKMouseClicked
        showFunction(3);
        Panel_QLTV.setBackground(new Color(0x1E2839));
        Panel_QLTB.setBackground(new Color(0x1E2839));
        Panel_QLVP.setBackground(new Color(0x1E2839));
        Panel_TK.setBackground(new Color(0x647187));
    }//GEN-LAST:event_Panel_TKMouseClicked

    private void Panel_QLTVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_QLTVMouseClicked
        Panel_QLTV.setBackground(new Color(0x647187));
        Panel_QLTB.setBackground(new Color(0x1E2839));
        Panel_QLVP.setBackground(new Color(0x1E2839));
        Panel_TK.setBackground(new Color(0x1E2839));
        showFunction(1);
    }//GEN-LAST:event_Panel_QLTVMouseClicked

    private void Panel_QLTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_QLTBMouseClicked
        showFunction(2);
        Panel_QLTV.setBackground(new Color(0x1E2839));
        Panel_QLTB.setBackground(new Color(0x647187));
        Panel_QLVP.setBackground(new Color(0x1E2839));
        Panel_TK.setBackground(new Color(0x1E2839));
    }//GEN-LAST:event_Panel_QLTBMouseClicked

    private void Panel_QLVPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_QLVPMouseClicked
       showFunction(4);
       Panel_QLTV.setBackground(new Color(0x1E2839));
       Panel_QLTB.setBackground(new Color(0x1E2839));
       Panel_QLVP.setBackground(new Color(0x647187));
       Panel_TK.setBackground(new Color(0x1E2839));
    }//GEN-LAST:event_Panel_QLVPMouseClicked

    public void showFunction(int x) {
        Content.removeAll();
        Content.setLayout(new BorderLayout());
        switch (x) {
            case 1: {
                QLThanhVien qlTV = new QLThanhVien();
                Content.add(qlTV);
                
                break;
            }
            case 2: {
                QLThietBi qlTB = new QLThietBi();
                Content.add(qlTB);
                break;
            }
            case 3: {
                ThongKe tK = new ThongKe();
                Content.add(tK);   
                break;
            }
            case 4: {
                QLViPham qlVP = new QLViPham();
                Content.add(qlVP);
                break;
            }
            case 5: {
                break;
            }
        }
        Content.revalidate();
        repaint();
        
        this.requestFocusInWindow();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel CloseBtn;
    private javax.swing.JPanel Content;
    private javax.swing.JLabel Label_QLTB;
    private javax.swing.JLabel Label_QLTB_icon;
    private javax.swing.JLabel Label_QLTV;
    private javax.swing.JLabel Label_QLTV_icon;
    private javax.swing.JLabel Label_TK;
    private javax.swing.JLabel Label_TK_icon;
    private javax.swing.JLabel Label_VP;
    private javax.swing.JLabel Label_VP_icon;
    private javax.swing.JPanel LeftMenu;
    private javax.swing.JPanel Panel_QLTB;
    private javax.swing.JPanel Panel_QLTV;
    private javax.swing.JPanel Panel_QLVP;
    private javax.swing.JPanel Panel_TK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
