/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BLL.ThanhVienBLL;
import BLL.ThietBiBLL;
import BLL.ThongTinSuDungBLL;
import DAL.Entities.ThanhVien;
import DAL.Entities.ThietBi;
import DAL.Entities.ThongTinSuDung;
import java.util.Date;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lamquoc
 */
public class MuonTraTB extends javax.swing.JPanel {

    private ThongTinSuDungBLL ttsdBLL = new ThongTinSuDungBLL();
    private Date date = new Date(System.currentTimeMillis());
    private ThanhVien tvMuon;
    private ThietBi thietBiMuon;
    private int maTTTra;

    /**
     * Creates new form MuonThietBi
     */
    public MuonTraTB() {
        initComponents();
        showAll();
    }

    public void showAll() {
        listThietBi();
        tbMuonThietBi();
        tbTraThietBi();
    }

    public void listThietBi() {
        ThietBiBLL tbBLL = new ThietBiBLL();
        DefaultListModel<String> model = new DefaultListModel<>(); // Tạo DefaultListModel mới

        for (ThietBi tb : tbBLL.getListThietBi()) {
            boolean check = true;
            for (ThongTinSuDung ttsd : ttsdBLL.getListThongTinSuDung()) {
                if (ttsd.getThietBi() != null && ttsd.getThietBi().equals(tb) && ttsd.getTgTra() == null) {
                    check = false;
                    break;
                }
            }
            if (check) {
                model.addElement(tb.getMaTB() + " - " + tb.getTenTB());
            }
        }

        listThietBi.setModel(model);
    }

    public void tbMuonThietBi() {
        DefaultTableModel model = (DefaultTableModel) tbMuonTB.getModel();
        model.setRowCount(0);
        for (ThongTinSuDung ttsd : ttsdBLL.getListThongTinSuDung()) {
            if (ttsd.getTgTra() != null) {
                Object[] object = {ttsd.getMaTT(), ttsd.getThanhVien().getMaTV(), ttsd.getThietBi().getMaTB(), ttsd.getTgMuon(), ttsd.getTgTra()};
                model.addRow(object);
            }
        }
        txtTGMuon.setText(String.valueOf(date));
    }

    public void tbTraThietBi() {
        DefaultTableModel model = (DefaultTableModel) tbTraTB.getModel();
        model.setRowCount(0);
        for (ThongTinSuDung ttsd : ttsdBLL.getListThongTinSuDung()) {
            if (ttsd.getTgMuon() != null && ttsd.getTgTra() == null) {
                Object[] object = {ttsd.getMaTT(), ttsd.getThanhVien().getMaTV(), ttsd.getThietBi().getMaTB(), ttsd.getTgMuon(), ttsd.getTgTra()};
                model.addRow(object);
            }
        }
    }

    public void reset() {
        txtMaTV.setText("");
        txtHoTen.setText("");
        txtKhoa.setText("");
        txtNganh.setText("");
        txtSDT.setText("");
        txtEmail.setText("");
        txtMaTT2.setText("");
        txtMaTV2.setText("");
        txtHoten2.setText("");
        txtMaTB2.setText("");
        txtTenTB2.setText("");
        txtMoTaTB2.setText("");
        txtTGMuon2.setText("");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabContent = new javax.swing.JTabbedPane();
        MuonTB = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtMaTV = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JLabel();
        txtNganh = new javax.swing.JLabel();
        txtKhoa = new javax.swing.JLabel();
        txtTGMuon = new javax.swing.JLabel();
        txtSDT = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbMuonTB = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listThietBi = new javax.swing.JList<>();
        btnXacNhan = new javax.swing.JButton();
        TraTB = new javax.swing.JPanel();
        dtgTGMuon = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTraTB = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaTV2 = new javax.swing.JLabel();
        txtHoten2 = new javax.swing.JLabel();
        txtMaTB2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTenTB2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTGMuon2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaTT2 = new javax.swing.JLabel();
        btnTra = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtMoTaTB2 = new javax.swing.JLabel();

        TabContent.setBackground(new java.awt.Color(153, 153, 153));
        TabContent.setForeground(new java.awt.Color(255, 255, 255));
        TabContent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabContent.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        TabContent.setPreferredSize(new java.awt.Dimension(862, 690));

        MuonTB.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Thông tin người mượn"));

        txtMaTV.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtMaTV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaTVKeyReleased(evt);
            }
        });

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNganh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtKhoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtTGMuon.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        txtTGMuon.setForeground(new java.awt.Color(51, 51, 0));

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jLabel8.setText("Mã thành viên:");

        jLabel9.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jLabel9.setText("Họ tên :");

        jLabel10.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jLabel10.setText("Khoa:");

        jLabel11.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jLabel11.setText("Số điện thoại:");

        jLabel12.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jLabel12.setText("Ngành");

        jLabel13.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jLabel13.setText("Giờ hiện tại:");

        jLabel14.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        jLabel14.setText("Email:");

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtKhoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTGMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNganh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtMaTV, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKhoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNganh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTGMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );

        tbMuonTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MãTT", "Mã TV", "Mã TB", "Thời gian mượn", "Thời gian trả"
            }
        ));
        jScrollPane3.setViewportView(tbMuonTB);
        if (tbMuonTB.getColumnModel().getColumnCount() > 0) {
            tbMuonTB.getColumnModel().getColumn(0).setMaxWidth(60);
            tbMuonTB.getColumnModel().getColumn(1).setMinWidth(80);
            tbMuonTB.getColumnModel().getColumn(2).setMinWidth(80);
        }

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Thiết bị"));

        listThietBi.setBorder(null);
        listThietBi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listThietBi.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Máy chiếu", "Máy ảnh", "Micro", "Laptop", "TV", "Tủ Lạnh ", "Máy Giặc" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listThietBi.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listThietBiValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listThietBi);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnXacNhan.setBackground(new java.awt.Color(0, 102, 0));
        btnXacNhan.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MuonTBLayout = new javax.swing.GroupLayout(MuonTB);
        MuonTB.setLayout(MuonTBLayout);
        MuonTBLayout.setHorizontalGroup(
            MuonTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MuonTBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MuonTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MuonTBLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(MuonTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MuonTBLayout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MuonTBLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MuonTBLayout.setVerticalGroup(
            MuonTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MuonTBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MuonTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MuonTBLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabContent.addTab("Mượn thiết bị", MuonTB);

        TraTB.setBackground(new java.awt.Color(255, 255, 255));

        dtgTGMuon.setBorder(javax.swing.BorderFactory.createTitledBorder("Thời gian mượn"));
        dtgTGMuon.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dtgTGMuonPropertyChange(evt);
            }
        });

        tbTraTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã TT", "Mã TV", "Mã TB", "Thời gian mượn"
            }
        ));
        tbTraTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTraTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTraTB);
        if (tbTraTB.getColumnModel().getColumnCount() > 0) {
            tbTraTB.getColumnModel().getColumn(0).setMaxWidth(50);
            tbTraTB.getColumnModel().getColumn(1).setMinWidth(150);
            tbTraTB.getColumnModel().getColumn(1).setMaxWidth(200);
            tbTraTB.getColumnModel().getColumn(2).setMinWidth(100);
            tbTraTB.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(153, 153, 153)));

        jLabel1.setText("Mã thành viên:");

        jLabel2.setText("Họ và tên:");

        jLabel3.setText("Mã thiết bị:");

        txtMaTV2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        txtHoten2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        txtMaTB2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel4.setText("Tên thiết bị:");

        txtTenTB2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel5.setText("Thời gian mượn:");

        txtTGMuon2.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Constantia", 3, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setLabelFor(jPanel1);
        jLabel6.setText("Mã TT");

        txtMaTT2.setFont(new java.awt.Font("DejaVu Serif", 1, 48)); // NOI18N
        txtMaTT2.setForeground(new java.awt.Color(153, 0, 51));
        txtMaTT2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMaTT2.setToolTipText("");

        btnTra.setBackground(new java.awt.Color(0, 102, 0));
        btnTra.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        btnTra.setForeground(new java.awt.Color(255, 255, 255));
        btnTra.setText("Xác nhận trả");
        btnTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraActionPerformed(evt);
            }
        });

        jLabel15.setText("Mô tả:");

        txtMoTaTB2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaTT2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHoten2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(txtMaTV2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtTGMuon2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4))
                                            .addComponent(jLabel15))
                                        .addGap(23, 23, 23)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTenTB2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                            .addComponent(txtMaTB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtMoTaTB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTra, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaTT2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaTV2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHoten2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaTB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTenTB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMoTaTB2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTGMuon2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTra, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout TraTBLayout = new javax.swing.GroupLayout(TraTB);
        TraTB.setLayout(TraTBLayout);
        TraTBLayout.setHorizontalGroup(
            TraTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TraTBLayout.createSequentialGroup()
                .addGroup(TraTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TraTBLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TraTBLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dtgTGMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TraTBLayout.setVerticalGroup(
            TraTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TraTBLayout.createSequentialGroup()
                .addGroup(TraTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TraTBLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(TraTBLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(dtgTGMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        TabContent.addTab("Trả thiết bị", TraTB);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabContent, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraActionPerformed
        // TODO add your handling code here:
        ttsdBLL.traThietBi(maTTTra, date);
        int choice = JOptionPane.showConfirmDialog(null, "Xác nhận trả?", "Trả thiết bị", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            if (maTTTra != -1) {
                ttsdBLL.traThietBi(maTTTra, date);
                listThietBi();
                tbTraThietBi();
                tbMuonThietBi();
                reset();
            } else {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn phiếu thông tin cần trả");
            }
        } else {
            return;
        }
    }//GEN-LAST:event_btnTraActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        if (tvMuon != null) {
            if (thietBiMuon != null) {
                ttsdBLL.muonThietBi(tvMuon, thietBiMuon, date);
                reset();
                listThietBi();
                tbTraThietBi();
            } else {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn thiết bị");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mã thành viên");
        }
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void tbTraTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTraTBMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbTraTB.getSelectedRow();

        if (selectedRow != -1) {
            String str = String.valueOf(tbTraTB.getValueAt(selectedRow, 0));
            maTTTra = Integer.parseInt(str);
            ThongTinSuDung ttsd = ttsdBLL.getThongTinSuDung(maTTTra);
            if (ttsd != null) {
                txtMaTT2.setText(String.valueOf(ttsd.getMaTT()));
                txtMaTV2.setText(String.valueOf(ttsd.getThanhVien().getMaTV()));
                txtHoten2.setText(String.valueOf(ttsd.getThanhVien().getHoTen()));
                txtMaTB2.setText(String.valueOf(ttsd.getThietBi().getMaTB()));
                txtTenTB2.setText(String.valueOf(ttsd.getThietBi().getTenTB()));
                txtMoTaTB2.setText(String.valueOf(ttsd.getThietBi().getMoTaTB()));
                txtTGMuon2.setText(String.valueOf(ttsd.getTgMuon()));
            }
        }
    }//GEN-LAST:event_tbTraTBMouseClicked

    private void txtMaTVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaTVKeyReleased
        // TODO add your handling code here:
        ThanhVienBLL tvBLL = new ThanhVienBLL();
        String input = txtMaTV.getText();
        if (!input.isEmpty() && input.matches("\\d+")) {
            try {
                Thread.sleep(500);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            tvMuon = tvBLL.getThanhVien(input);
            if (tvMuon != null) {
                txtHoTen.setText(tvMuon.getHoTen());
                txtKhoa.setText(tvMuon.getKhoa());
                txtNganh.setText(tvMuon.getNganh());
                txtSDT.setText(tvMuon.getSDT());
                txtEmail.setText(tvMuon.getEmail());
            }
        }
    }//GEN-LAST:event_txtMaTVKeyReleased

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnClearActionPerformed

    private void listThietBiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listThietBiValueChanged
        // TODO add your handling code here:
        if (!evt.getValueIsAdjusting()) {
            String selectedThietBi = listThietBi.getSelectedValue();
            if (selectedThietBi != null) {
                String[] part = selectedThietBi.split(" - ");
                int maTB = Integer.parseInt(part[0]);
                ThietBiBLL tbBLL = new ThietBiBLL();
                thietBiMuon = tbBLL.getThietBi(maTB);
            }
        }
    }//GEN-LAST:event_listThietBiValueChanged

    private void dtgTGMuonPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dtgTGMuonPropertyChange
        // TODO add your handling code here:
        Date TGMuon = dtgTGMuon.getDate();
    }//GEN-LAST:event_dtgTGMuonPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MuonTB;
    private javax.swing.JTabbedPane TabContent;
    private javax.swing.JPanel TraTB;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnTra;
    private javax.swing.JButton btnXacNhan;
    private com.toedter.calendar.JDateChooser dtgTGMuon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listThietBi;
    private javax.swing.JTable tbMuonTB;
    private javax.swing.JTable tbTraTB;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtHoTen;
    private javax.swing.JLabel txtHoten2;
    private javax.swing.JLabel txtKhoa;
    private javax.swing.JLabel txtMaTB2;
    private javax.swing.JLabel txtMaTT2;
    private javax.swing.JTextField txtMaTV;
    private javax.swing.JLabel txtMaTV2;
    private javax.swing.JLabel txtMoTaTB2;
    private javax.swing.JLabel txtNganh;
    private javax.swing.JLabel txtSDT;
    private javax.swing.JLabel txtTGMuon;
    private javax.swing.JLabel txtTGMuon2;
    private javax.swing.JLabel txtTenTB2;
    // End of variables declaration//GEN-END:variables
}
